In [1]:
import idlelib.replace

import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credit = pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
movies = movies.merge(credit, on='title')

In [5]:
# genres
# id
# keywords
# tittle
# overview
# cast
# crew

In [6]:
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [7]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [8]:
movies.dropna(inplace=True)

In [9]:
movies.duplicated().sum()

np.int64(0)

In [10]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [11]:
import ast

In [12]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i["name"])
    return L

In [13]:
movies["genres"] = movies["genres"].apply(convert)

In [14]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
movies["keywords"] = movies["keywords"].apply(convert)

In [16]:
movies["cast"][9]

'[{"cast_id": 18, "character": "Bruce Wayne / Batman", "credit_id": "52fe4d5bc3a368484e1e4c65", "gender": 2, "id": 880, "name": "Ben Affleck", "order": 0}, {"cast_id": 14, "character": "Clark Kent / Superman", "credit_id": "52fe4d5bc3a368484e1e4c55", "gender": 2, "id": 73968, "name": "Henry Cavill", "order": 1}, {"cast_id": 19, "character": "Diana Prince / Wonder Woman", "credit_id": "52fe4d5bc3a368484e1e4c69", "gender": 1, "id": 90633, "name": "Gal Gadot", "order": 2}, {"cast_id": 15, "character": "Lois Lane", "credit_id": "52fe4d5bc3a368484e1e4c59", "gender": 1, "id": 9273, "name": "Amy Adams", "order": 3}, {"cast_id": 22, "character": "Lex Luthor", "credit_id": "52fe4d5bc3a368484e1e4c79", "gender": 2, "id": 44735, "name": "Jesse Eisenberg", "order": 4}, {"cast_id": 17, "character": "Martha Kent", "credit_id": "52fe4d5bc3a368484e1e4c61", "gender": 1, "id": 2882, "name": "Diane Lane", "order": 5}, {"cast_id": 23, "character": "Alfred Pennyworth", "credit_id": "52fe4d5bc3a368484e1e4c7d", "gender": 0, "id": 16940, "name": "Jeremy Irons", "order": 6}, {"cast_id": 16, "character": "Perry White", "credit_id": "52fe4d5bc3a368484e1e4c5d", "gender": 2, "id": 2975, "name": "Laurence Fishburne", "order": 7}, {"cast_id": 26, "character": "Senator Finch", "credit_id": "533d9aeec3a36878ed0035ec", "gender": 1, "id": 18686, "name": "Holly Hunter", "order": 8}, {"cast_id": 33, "character": "Wallace Keefe", "credit_id": "53ac7a9a0e0a26598600036e", "gender": 2, "id": 59233, "name": "Scoot McNairy", "order": 9}, {"cast_id": 24, "character": "Anatoli Knyazev", "credit_id": "533d9abdc3a36878e600358f", "gender": 2, "id": 208296, "name": "Callan Mulvey", "order": 10}, {"cast_id": 25, "character": "Mercy Graves", "credit_id": "533d9acec3a36878e6003591", "gender": 1, "id": 1156024, "name": "Tao Okamoto", "order": 11}, {"cast_id": 270, "character": "Jenet Klyburn", "credit_id": "58cc0f95c3a368289901360f", "gender": 1, "id": 20089, "name": "Jena Malone", "order": 12}, {"cast_id": 61, "character": "Young Bruce Wayne", "credit_id": "56f79273c3a3686a5e0065eb", "gender": 2, "id": 1511243, "name": "Brandon Spink", "order": 13}, {"cast_id": 54, "character": "Martha Wayne", "credit_id": "56a329f5c3a368389b0021d7", "gender": 1, "id": 62220, "name": "Lauren Cohan", "order": 14}, {"cast_id": 76, "character": "Jack O\'Dwyer", "credit_id": "5762f5169251415b940000eb", "gender": 2, "id": 87447, "name": "Hugh Maguire", "order": 15}, {"cast_id": 60, "character": "Jimmy Olsen", "credit_id": "56f791fd9251412cc0002d12", "gender": 2, "id": 56556, "name": "Michael Cassidy", "order": 16}, {"cast_id": 161, "character": "Wayne Industries Pilot", "credit_id": "57fa30b2925141212b006e11", "gender": 2, "id": 1106260, "name": "Alan D. Purwin", "order": 17}, {"cast_id": 77, "character": "Drone Pilot", "credit_id": "5762f569c3a3684b630000e3", "gender": 0, "id": 1190987, "name": "Dan Amboyer", "order": 18}, {"cast_id": 62, "character": "Jenny Jurwich", "credit_id": "56f7934cc3a3686a670062e5", "gender": 0, "id": 1272969, "name": "Rebecca Buller", "order": 19}, {"cast_id": 63, "character": "General Swanwick", "credit_id": "56f7938792514120f8000015", "gender": 2, "id": 9464, "name": "Harry Lennix", "order": 20}, {"cast_id": 64, "character": "Major Carrie Farris", "credit_id": "56f7939b92514120f800001a", "gender": 0, "id": 1272970, "name": "Christina Wren", "order": 21}, {"cast_id": 75, "character": "Carmen", "credit_id": "573e5c7592514108d700058f", "gender": 1, "id": 1622651, "name": "Jade Chynoweth", "order": 22}, {"cast_id": 68, "character": "Glen Woodburn", "credit_id": "56f7943592514120f8000036", "gender": 0, "id": 91403, "name": "Chad Krowchuk", "order": 23}, {"cast_id": 56, "character": "Jonathan Kent", "credit_id": "56f33c339251411a85000bd3", "gender": 2, "id": 1269, "name": "Kevin Costner", "order": 24}, {"cast_id": 58, "character": "Barry Allen / The Flash", "credit_id": "56f50fe6c3a368273e001d57", "gender": 2, "id": 132157, "name": "Ezra Miller", "order": 25}, {"cast_id": 73, "character": "POTUS (voice)", "credit_id": "56f794f692514120f8000056", "gender": 2, "id": 17178, "name": "Patrick Wilson", "order": 26}, {"cast_id": 53, "character": "General Zod", "credit_id": "5692a01fc3a3685c54000252", "gender": 2, "id": 335, "name": "Michael Shannon", "order": 27}, {"cast_id": 67, "character": "Himself", "credit_id": "56f7941f9251412fdd001ddc", "gender": 2, "id": 70177, "name": "Charlie Rose", "order": 28}, {"cast_id": 65, "character": "Himself", "credit_id": "56f793e79251411a61003e24", "gender": 2, "id": 1018992, "name": "Vikram Gandhi", "order": 29}, {"cast_id": 66, "character": "Himself", "credit_id": "56f79416c3a3686a5e00662c", "gender": 2, "id": 1236584, "name": "Andrew Sullivan", "order": 30}, {"cast_id": 69, "character": "Himself", "credit_id": "56f79445c3a3686a5c005e1b", "gender": 2, "id": 550307, "name": "Neil deGrasse Tyson", "order": 31}, {"cast_id": 79, "character": "Himself", "credit_id": "5762f63cc3a3684b87000104", "gender": 2, "id": 12219, "name": "Jon Stewart", "order": 32}, {"cast_id": 70, "character": "Herself", "credit_id": "56f7945ec3a3686a61005b16", "gender": 0, "id": 1227867, "name": "Soledad O\'Brien", "order": 33}, {"cast_id": 215, "character": "Herself", "credit_id": "58051dcac3a3681da6001394", "gender": 1, "id": 1696036, "name": "Erika R. Erickson", "order": 34}, {"cast_id": 71, "character": "Herself", "credit_id": "56f7947592514120f8000047", "gender": 1, "id": 1596937, "name": "Dana Bash", "order": 35}, {"cast_id": 72, "character": "Herself", "credit_id": "56f794b392514169e2003791", "gender": 1, "id": 1514160, "name": "Nancy Grace", "order": 36}, {"cast_id": 59, "character": "Himself", "credit_id": "56f725109251412fdd0009c0", "gender": 0, "id": 1217309, "name": "Anderson Cooper", "order": 37}, {"cast_id": 216, "character": "Herself", "credit_id": "58051f59c3a3681dbd001413", "gender": 1, "id": 1696037, "name": "Brooke Baldwin", "order": 38}, {"cast_id": 57, "character": "A.I. Kelor (voice)", "credit_id": "56f33c499251415fc60001d8", "gender": 1, "id": 17832, "name": "Carla Gugino", "order": 39}, {"cast_id": 32, "character": "Arthur Curry / Aquaman", "credit_id": "539f1af4c3a368280b000344", "gender": 2, "id": 117642, "name": "Jason Momoa", "order": 40}, {"cast_id": 74, "character": "Silas Stone", "credit_id": "56f7952dc3a3686a5c005e3c", "gender": 2, "id": 3977, "name": "Joe Morton", "order": 41}, {"cast_id": 27, "character": "Victor Stone / Cyborg", "credit_id": "535a8513c3a368308a00003b", "gender": 2, "id": 1313559, "name": "Ray Fisher", "order": 42}, {"cast_id": 80, "character": "Pete Ross", "credit_id": "5762f6fac3a3684b6f00011c", "gender": 2, "id": 1636956, "name": "Joseph Cranford", "order": 43}, {"cast_id": 81, "character": "Lana Lang", "credit_id": "5762f70bc3a3684b60000148", "gender": 0, "id": 1377087, "name": "Emily Peterson", "order": 44}, {"cast_id": 49, "character": "Thomas Wayne", "credit_id": "55c57fadc3a3682f21000cbe", "gender": 2, "id": 47296, "name": "Jeffrey Dean Morgan", "order": 45}, {"cast_id": 83, "character": "General Amajagh", "credit_id": "57a182a1c3a3686877004d25", "gender": 2, "id": 19300, "name": "Sammi Rotibi", "order": 46}, {"cast_id": 162, "character": "Metropolis Citizen", "credit_id": "57fa33f2c3a3686ffa007dfa", "gender": 1, "id": 1467216, "name": "Hanna Dworkin", "order": 47}, {"cast_id": 163, "character": "Metropolis Citizen", "credit_id": "57fa3753c3a3681b7f005be7", "gender": 1, "id": 1691930, "name": "Tiffany L. Addison", "order": 48}, {"cast_id": 164, "character": "Metropolis Citizen", "credit_id": "57fa3896c3a3681b8f0061c3", "gender": 2, "id": 1471446, "name": "Owais Ahmed", "order": 49}, {"cast_id": 165, "character": "Metropolis Citizen", "credit_id": "57fa390d9251411fb3006b9f", "gender": 2, "id": 1691935, "name": "Anish Jethmalani", "order": 50}, {"cast_id": 166, "character": "Metropolis Citizen", "credit_id": "57fa39b79251411fd3006b7d", "gender": 1, "id": 1691940, "name": "Tiffany Bedwell", "order": 51}, {"cast_id": 167, "character": "Metropolis Citizen", "credit_id": "57fa3ac29251412128006f64", "gender": 1, "id": 1691945, "name": "Natalee Arteaga", "order": 52}, {"cast_id": 168, "character": "Metropolis Citizen", "credit_id": "57fa3acfc3a3686ffa00817a", "gender": 2, "id": 1691946, "name": "Keith D. Gallagher", "order": 53}, {"cast_id": 169, "character": "Metropolis Citizen", "credit_id": "57fa440cc3a3686ffa008699", "gender": 2, "id": 1691967, "name": "Jeff Dumas", "order": 54}, {"cast_id": 170, "character": "Metropolis Citizen", "credit_id": "57fa4693c3a3686fed007f7e", "gender": 1, "id": 1682540, "name": "Miriam Lee", "order": 55}, {"cast_id": 171, "character": "Metropolis Citizen", "credit_id": "57fa470592514120c5006e77", "gender": 1, "id": 1691970, "name": "Alicia Regan", "order": 56}, {"cast_id": 172, "character": "Teacher", "credit_id": "57fa47e0c3a36818af006629", "gender": 1, "id": 1395056, "name": "Stephanie Koenig", "order": 57}, {"cast_id": 173, "character": "Sage", "credit_id": "57fa4802c3a36818af006638", "gender": 1, "id": 1648751, "name": "Ripley Sobo", "order": 58}, {"cast_id": 174, "character": "Island Scientist", "credit_id": "57fa4a6bc3a3686fff008959", "gender": 2, "id": 1691971, "name": "Richard Burden", "order": 59}, {"cast_id": 175, "character": "General Security Chief", "credit_id": "57fa50dd9251411fb300776b", "gender": 2, "id": 156405, "name": "Julius Tennon", "order": 60}, {"cast_id": 176, "character": "Kahina Ziri", "credit_id": "57fa53b9c3a3686fff008eb7", "gender": 0, "id": 134774, "name": "Wunmi Mosaku", "order": 61}, {"cast_id": 177, "character": "Senator Barrows", "credit_id": "57fa56889251412128007d8f", "gender": 2, "id": 1561391, "name": "Dennis North", "order": 62}, {"cast_id": 178, "character": "Officer Mazzuccheli", "credit_id": "57fa586a9251411fd3007af0", "gender": 0, "id": 1141368, "name": "Kiff VandenHeuvel", "order": 63}, {"cast_id": 179, "character": "Officer Rucka", "credit_id": "57fa58a5c3a3686ffa00916e", "gender": 2, "id": 1561419, "name": "Mason Heidger", "order": 64}, {"cast_id": 180, "character": "Hostage Girl", "credit_id": "57fa5ac39251411fd3007c0e", "gender": 1, "id": 74312, "name": "Ahney Her", "order": 65}, {"cast_id": 181, "character": "Hostage Girl", "credit_id": "57fa5d30925141212b0084bf", "gender": 1, "id": 1691981, "name": "Kristine Cabanban", "order": 66}, {"cast_id": 182, "character": "Cesar Santos", "credit_id": "57fa5dd1c3a3681b8f007324", "gender": 2, "id": 53066, "name": "Sebastian Sozzi", "order": 67}, {"cast_id": 183, "character": "Himself", "credit_id": "57fa5de992514120f9007e96", "gender": 2, "id": 79086, "name": "Kent Shocknek", "order": 68}, {"cast_id": 184, "character": "Emmet Vale", "credit_id": "57fa5e0192514120c5007969", "gender": 2, "id": 1494289, "name": "Ralph Lister", "order": 69}, {"cast_id": 185, "character": "Metropolis Cop", "credit_id": "57fa5f2bc3a3686fed008bb6", "gender": 2, "id": 1691982, "name": "Sammy A. Publes", "order": 70}, {"cast_id": 186, "character": "Metropolis Cop", "credit_id": "57fa6081c3a3681bff00741b", "gender": 2, "id": 1691983, "name": "Jay R. Adams", "order": 71}, {"cast_id": 187, "character": "Hero\'s Park Tourist", "credit_id": "57fa63cbc3a3681b7f006ef0", "gender": 2, "id": 1691986, "name": "David Midura", "order": 72}, {"cast_id": 188, "character": "Reporter at Monument", "credit_id": "57fa64e292514120f90081e7", "gender": 2, "id": 1691987, "name": "Jay Towers", "order": 73}, {"cast_id": 189, "character": "Air Force MP", "credit_id": "57fa6b01925141016200942f", "gender": 0, "id": 1395050, "name": "Michael Ellison", "order": 74}, {"cast_id": 190, "character": "Underground Fight Patron", "credit_id": "57fa6ca4c3a3686fff009c06", "gender": 2, "id": 1692027, "name": "Kirill Ostapenko", "order": 75}, {"cast_id": 191, "character": "Beautiful Woman", "credit_id": "57fa7179c3a3686fff009ea9", "gender": 1, "id": 1692036, "name": "Rashontae Wawrzyniak", "order": 76}, {"cast_id": 192, "character": "Sports Announcer", "credit_id": "57fa732cc3a3681b8f007d91", "gender": 2, "id": 1214961, "name": "Tom Luginbill", "order": 77}, {"cast_id": 193, "character": "Sports Announcer", "credit_id": "57fa749cc3a3681b8f007e2d", "gender": 2, "id": 1692048, "name": "Dave Pasch", "order": 78}, {"cast_id": 194, "character": "Party Photographer", "credit_id": "57fa7528c3a3686fff00a0df", "gender": 2, "id": 146413, "name": "Danny Mooney ", "order": 79}, {"cast_id": 195, "character": "Party Doorman", "credit_id": "57fa7541c3a3681b8f007e6d", "gender": 2, "id": 1692050, "name": "Henry Frost III", "order": 80}, {"cast_id": 196, "character": "LeBlanc", "credit_id": "57fa755a92514120c50085df", "gender": 1, "id": 165293, "name": "Nicole Forester", "order": 81}, {"cast_id": 197, "character": "Metropolis Governor", "credit_id": "5804fddcc3a36868a7001204", "gender": 1, "id": 1695971, "name": "Debbie Stabenow", "order": 82}, {"cast_id": 198, "character": "Colorado Woman", "credit_id": "5805063ac3a3681db30004d6", "gender": 0, "id": 146412, "name": "Milica Govich ", "order": 83}, {"cast_id": 199, "character": "Jail Guard", "credit_id": "58050955c3a3681dba00070b", "gender": 2, "id": 1695987, "name": "John Lepard", "order": 84}, {"cast_id": 200, "character": "Finch\'s Receptionist", "credit_id": "58050a47c3a3681dba0007bf", "gender": 1, "id": 1695988, "name": "Sandra Love Aldridge", "order": 85}, {"cast_id": 201, "character": "James Harmon - Museum Director", "credit_id": "58050bc492514170a700094b", "gender": 2, "id": 1695990, "name": "Graham W.J. Beal", "order": 86}, {"cast_id": 202, "character": "Bunker Soldier", "credit_id": "58050c8fc3a3681dac0008ad", "gender": 2, "id": 1695991, "name": "Henri Franklin", "order": 87}, {"cast_id": 203, "character": "Bunker Soldier", "credit_id": "58050dfec3a3681dbd0009e6", "gender": 2, "id": 1289444, "name": "Jonathan West", "order": 88}, {"cast_id": 204, "character": "US Park Officer", "credit_id": "58050ee6c3a3681dac0009f5", "gender": 2, "id": 1695992, "name": "T.J. Martinelli", "order": 89}, {"cast_id": 205, "character": "Wayne Accountant", "credit_id": "5805103692514170a7000c11", "gender": 2, "id": 1561416, "name": "Chris Newman", "order": 90}, {"cast_id": 208, "character": "Diner Waitress", "credit_id": "58051489c3a3681dbd000dc7", "gender": 1, "id": 1696013, "name": "Lulu Dahl", "order": 91}, {"cast_id": 206, "character": "DC Protestor", "credit_id": "580512eac3a3681da6000d3c", "gender": 2, "id": 1201979, "name": "Sam Logan Khaleghi", "order": 92}, {"cast_id": 209, "character": "DC Protestor", "credit_id": "5805171c92514170aa00107d", "gender": 1, "id": 1696018, "name": "Anne Marie Damman", "order": 93}, {"cast_id": 210, "character": "DC Protestor", "credit_id": "5805172f92514170b7001010", "gender": 0, "id": 1452211, "name": "Connie Craig", "order": 94}, {"cast_id": 211, "character": "DC Protestor", "credit_id": "580517e2c3a3681db60010a6", "gender": 1, "id": 1696019, "name": "Henrietta Hermelin", "order": 95}, {"cast_id": 212, "character": "Senator Purrington", "credit_id": "58051a4692514170b70011c7", "gender": 2, "id": 853194, "name": "Patrick Leahy", "order": 96}, {"cast_id": 213, "character": "Convenience Store Robber", "credit_id": "58051b3a92514170b4001156", "gender": 2, "id": 1334323, "name": "Albert Valladares", "order": 97}, {"cast_id": 214, "character": "Helicopter Pilot", "credit_id": "58051ca4c3a3681db60013bb", "gender": 2, "id": 1685460, "name": "David Paris", "order": 98}, {"cast_id": 217, "character": "Flight Attendant", "credit_id": "58051fc0c3a3681da600148f", "gender": 1, "id": 1696038, "name": "Abigail Kuklis", "order": 99}, {"cast_id": 218, "character": "Chairman of Joint Chiefs", "credit_id": "5805f5c59251415bbe004133", "gender": 0, "id": 1545503, "name": "Greg Violand", "order": 100}, {"cast_id": 219, "character": "Vice Chairman of Joint Chiefs", "credit_id": "5805f5da9251415bec004209", "gender": 2, "id": 1007391, "name": "Tiren Jhames", "order": 101}, {"cast_id": 220, "character": "Signals Officer - Air Force", "credit_id": "5805f89cc3a3684cba003b04", "gender": 2, "id": 1505007, "name": "Steve Jasgur", "order": 102}, {"cast_id": 221, "character": "Silo Officer", "credit_id": "5805f9239251415b9000472e", "gender": 2, "id": 1696221, "name": "Jonathan Stanley", "order": 103}, {"cast_id": 222, "character": "Silo Officer", "credit_id": "5805fa289251415a7a0045e3", "gender": 2, "id": 1390506, "name": "Jesse Nagy", "order": 104}, {"cast_id": 223, "character": "Supermax Guard", "credit_id": "5805fc42c3a3684ee5004b70", "gender": 2, "id": 1696222, "name": "Duvale Murchison", "order": 105}, {"cast_id": 224, "character": "Prison Barber", "credit_id": "5805fda8c3a3684ee5004cf1", "gender": 2, "id": 1696223, "name": "Thomas J. Fentress", "order": 106}, {"cast_id": 225, "character": "Father Leone", "credit_id": "5805fe9f9251415bec004b25", "gender": 0, "id": 1189226, "name": "Coburn Goss", "order": 107}, {"cast_id": 226, "character": "Wagon Driver", "credit_id": "5805febe92514170b700c0ec", "gender": 0, "id": 1696226, "name": "Jeff Hanlin", "order": 108}, {"cast_id": 227, "character": "Creature Vocals (voice)", "credit_id": "5806000fc3a3684cba00417a", "gender": 2, "id": 1077782, "name": "Gary A. Hecker", "order": 109}, {"cast_id": 228, "character": "Kreatur (voice)", "credit_id": "580600c5c3a3684d4e0047c2", "gender": 2, "id": 130081, "name": "Robin Atkin Downes", "order": 110}, {"cast_id": 229, "character": "Squatter Boy", "credit_id": "58060193c3a3684f1a0049be", "gender": 2, "id": 1696230, "name": "Issac Ryan Brown", "order": 111}, {"cast_id": 230, "character": "CIA Supervisor", "credit_id": "580601d49251415bbe004cc4", "gender": 2, "id": 1374130, "name": "Barton Bund", "order": 112}, {"cast_id": 231, "character": "Python Team Leader", "credit_id": "580602c5c3a3684d4e004942", "gender": 2, "id": 104195, "name": "Bailey Chase", "order": 113}, {"cast_id": 232, "character": "Gotham Desk Cop", "credit_id": "5806049c9251415a8600523f", "gender": 2, "id": 1696231, "name": "Patrick O\'Connor Cronin", "order": 114}, {"cast_id": 233, "character": "Gotham Desk Cop", "credit_id": "580606e3c3a3684d4e004c05", "gender": 1, "id": 1000800, "name": "Sonja Crosby", "order": 115}, {"cast_id": 234, "character": "Inmate Thug", "credit_id": "580608a5c3a3684cba004729", "gender": 2, "id": 1696234, "name": "C.T. Fletcher", "order": 116}, {"cast_id": 239, "character": "Inmate Thug", "credit_id": "58060bda9251415ab0005ad0", "gender": 2, "id": 1696241, "name": "Ahman Green", "order": 117}, {"cast_id": 235, "character": "Nairomian Crying Woman", "credit_id": "580609f99251415a5400578c", "gender": 0, "id": 1548735, "name": "Diana Gaitirira", "order": 118}, {"cast_id": 242, "character": "Nairomian Crying Woman", "credit_id": "58060ec09251415ab0005d5f", "gender": 1, "id": 1147413, "name": "Jalene Mack", "order": 119}, {"cast_id": 236, "character": "Nairomian Crying Woman", "credit_id": "58060a0c9251415a7a00531c", "gender": 1, "id": 1424325, "name": "Esodie Geiger", "order": 120}, {"cast_id": 245, "character": "Nairomian Crying Woman", "credit_id": "58061229c3a3684cba004d62", "gender": 1, "id": 1696264, "name": "Nene Nwoko", "order": 121}, {"cast_id": 240, "character": "Nairomian Driver", "credit_id": "58060e28c3a3684f1a005296", "gender": 2, "id": 1696251, "name": "Scott Edward Logan", "order": 122}, {"cast_id": 237, "character": "Gala Waiter", "credit_id": "58060a2092514170b700c90f", "gender": 2, "id": 1696236, "name": "Marcus Goddard", "order": 123}, {"cast_id": 238, "character": "Adriana Santos", "credit_id": "58060b2ac3a3684e06005947", "gender": 1, "id": 1696238, "name": "Cruz Gonzalez-Cadel", "order": 124}, {"cast_id": 243, "character": "Older Goat Herder", "credit_id": "58060eedc3a3684ee5005a7e", "gender": 1, "id": 162169, "name": "Alma Martinez", "order": 125}, {"cast_id": 241, "character": "Older Goat Herder", "credit_id": "58060e3fc3a3684cba004ae0", "gender": 0, "id": 8666, "name": "Sal Lopez", "order": 126}, {"cast_id": 247, "character": "Young Goat Herder", "credit_id": "58061399c3a3684e06005f7a", "gender": 0, "id": 1696268, "name": "Marcel Sh

In [17]:
def convert3(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i["name"])
            counter += 1
        else:
            break
    return L

In [18]:
movies["cast"] = movies["cast"].apply(convert3)

In [19]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i["job"] == "Director":
            L.append(i["name"])
            break
    return L

In [20]:
movies["crew"] = movies["crew"].apply(fetch_director)

In [21]:
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns]
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith]
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia]
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]",[Brian Herzlinger]

In [22]:
movies["overview"] = movies["overview"].apply(lambda x: x.split())

In [23]:
movies["genres"] = movies["genres"].apply(lambda x: [i.replace(" ","") for i in x])
movies["keywords"] = movies["keywords"].apply(lambda x: [i.replace(" ","") for i in x])
movies["cast"] = movies["cast"].apply(lambda x: [i.replace(" ","") for i in x])
movies["crew"] = movies["crew"].apply(lambda x: [i.replace(" ","") for i in x])

In [24]:
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez]
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns]
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith]
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia]
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger]

In [25]:
movies["tags"] = movies["overview"] + movies["genres"] + movies["cast"] + movies["crew"]

In [26]:
movies

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez],"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance]",[],"[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns],"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie]","[date, loveatfirstsight, narration, investigat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith],"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],[],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia],"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...",[Documentary],"[obsession, camcorder, crush, dreamgirl]","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger],"[Ever, since, the, second, grade, when, he, fi..."

In [27]:
df = movies[["movie_id", "title", "tags"]]

In [28]:
df["tags"] = df["tags"].apply(lambda x: " ".join(x))

In [29]:
df["tags"] = df["tags"].apply(lambda x: x.lower())

In [30]:
df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words="english")

In [32]:
vectors = cv.fit_transform(df["tags"]).toarray()

In [33]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [34]:
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()

In [35]:
def stem(text):
    y = []
    for i in text.split():
        y.append(porter.stem(i))

    return " ".join(y)

In [36]:
 stem(df["tags"][0])

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav jamescameron'

In [37]:
df["tags"] =  df["tags"].apply(stem)

In [38]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [39]:
def recommend(movie):
    index = df[df['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(df.iloc[i[0]].title)

In [40]:
recommend("Batman Begins")

The Dark Knight Rises
Amidst the Devil's Wings
The Dark Knight
Batman
Dead Man Down

In [44]:
import pickle
pickle.dump(df, open("movie.pkl", "wb"))

In [45]:
pickle.dump(similarity, open("similarity.pkl","wb"))